//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace asm.Windows.Actipro.Properties {
	/// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("asm.Windows.Actipro.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SyntaxLanguage Key=&quot;BatchFile&quot; LanguageDefinitionVersion=&quot;4.0&quot; Secure=&quot;True&quot; xmlns=&quot;http://ActiproSoftware/SyntaxEditor/4.0/LanguageDefinition&quot;&gt;
        ///
        ///	&lt;!-- String Properties --&gt;
        ///	&lt;Properties&gt;
        ///		&lt;Property Key=&quot;Creator&quot; Value=&quot;Actipro Software LLC&quot; /&gt;
        ///		&lt;Property Key=&quot;Copyright&quot; Value=&quot;Copyright (c) 2001-2014 Actipro Software LLC.  All rights reserved.&quot; /&gt;
        ///	&lt;/Properties&gt;
        ///
        ///	&lt;!-- Highlighting Styles --&gt;	
        ///	&lt;Styles&gt;
        ///		&lt;Style Key=&quot;ReservedWordStyle&quot; ForeColor=&quot;Blue&quot; /&gt;
        ///		&lt;Style Key=&quot;LabelStyle&quot; ForeColor=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LexerBatchFile {
            get {
                return ResourceManager.GetString("LexerBatchFile", resourceCulture);
            }
        }
    }
}
