using asm.Globalization;

namespace asm.Media.Youtube
{
	public class ClosedCaptionTrackInfo
	{
		public ClosedCaptionTrackInfo()
		{
		}

		public string Url { get; internal set; }

		public Language Language { get; internal set; }

		public bool IsAutoGenerated { get; internal set; }
	}
}