//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asm.Exceptions.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("asm.Exceptions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer is not large enough for the requested data..
        /// </summary>
        internal static string BufferNotLargeEnough {
            get {
                return ResourceManager.GetString("BufferNotLargeEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection is locked..
        /// </summary>
        internal static string CollectionLocked {
            get {
                return ResourceManager.GetString("CollectionLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compression error..
        /// </summary>
        internal static string CompressionError {
            get {
                return ResourceManager.GetString("CompressionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compression failed..
        /// </summary>
        internal static string CompressionFailed {
            get {
                return ResourceManager.GetString("CompressionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture is not supported..
        /// </summary>
        internal static string CultureNotSupported {
            get {
                return ResourceManager.GetString("CultureNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key already exists..
        /// </summary>
        internal static string DuplicateKey {
            get {
                return ResourceManager.GetString("DuplicateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extraction failed..
        /// </summary>
        internal static string ExtractionFailed {
            get {
                return ResourceManager.GetString("ExtractionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination image has different size or pixel format..
        /// </summary>
        internal static string ImagePropertiesMismatch {
            get {
                return ResourceManager.GetString("ImagePropertiesMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid archive..
        /// </summary>
        internal static string InvalidArchive {
            get {
                return ResourceManager.GetString("InvalidArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file name..
        /// </summary>
        internal static string InvalidFileName {
            get {
                return ResourceManager.GetString("InvalidFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid handle..
        /// </summary>
        internal static string InvalidHandle {
            get {
                return ResourceManager.GetString("InvalidHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The unmanaged image has some invalid properties, therefore it cannot be converted to a managed image..
        /// </summary>
        internal static string InvalidImageProperties {
            get {
                return ResourceManager.GetString("InvalidImageProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SFX settings validation failed..
        /// </summary>
        internal static string InvalidSfxSettings {
            get {
                return ResourceManager.GetString("InvalidSfxSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item is fixed..
        /// </summary>
        internal static string ItemFixed {
            get {
                return ResourceManager.GetString("ItemFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item is locked..
        /// </summary>
        internal static string ItemLocked {
            get {
                return ResourceManager.GetString("ItemLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library could not be loaded..
        /// </summary>
        internal static string LibraryNotLoaded {
            get {
                return ResourceManager.GetString("LibraryNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit has been reached..
        /// </summary>
        internal static string LimitReached {
            get {
                return ResourceManager.GetString("LimitReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not connected..
        /// </summary>
        internal static string NotConnected {
            get {
                return ResourceManager.GetString("NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item not found..
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotMethodExpression.
        /// </summary>
        internal static string NotMethodExpression {
            get {
                return ResourceManager.GetString("NotMethodExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is not safe to cache..
        /// </summary>
        internal static string NotSafeToCache {
            get {
                return ResourceManager.GetString("NotSafeToCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of type &apos;{0}&apos; is not safe to cache..
        /// </summary>
        internal static string NotSafeTypeToCache {
            get {
                return ResourceManager.GetString("NotSafeTypeToCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified stream is not a valid LZMA stream..
        /// </summary>
        internal static string NotValidLZMAStream {
            get {
                return ResourceManager.GetString("NotValidLZMAStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SevenZip unknown exception..
        /// </summary>
        internal static string SevenZipException {
            get {
                return ResourceManager.GetString("SevenZipException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixel format is not supported..
        /// </summary>
        internal static string UnsupportedImageFormat {
            get {
                return ResourceManager.GetString("UnsupportedImageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is not an enumeration type..
        /// </summary>
        internal static string ValueIsNotEnumType {
            get {
                return ResourceManager.GetString("ValueIsNotEnumType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of type &apos;{0}&apos; is not an enumeration type..
        /// </summary>
        internal static string ValueTypeIsNotEnumType {
            get {
                return ResourceManager.GetString("ValueTypeIsNotEnumType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection version changed..
        /// </summary>
        internal static string VersionChanged {
            get {
                return ResourceManager.GetString("VersionChanged", resourceCulture);
            }
        }
    }
}
