name: Release to NuGet

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        env:
            BUILD_CONFIG: "Release"
            SOLUTION: "essentialMix.sln"
            OUTPUT: "./nuget"

        runs-on: ubuntu-latest
        timeout-minutes: 5

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup .NET SDK
              uses: actions/setup-dotnet@v1

            - name: Build
              run: dotnet build -c Release

            - name: Test
              run: dotnet test -c Release --no-build

            - name: Pack nugets
              run: dotnet pack -c Release --no-build --output ${{env.output}}

            - name: Push to NuGet
              run: dotnet nuget push "${{env.output}}/*.nupkg" -s https://api.nuget.org/v3/index.json --skip-duplicate -k ${{secrets.nuget_api_key}}
